### ISSUE TITLE
Batch archival fails

### ISSUE THREAD

**Issue by wetneb** [Wikidata/editgroups#108]
Likely become of an out of memory error:

```
[2024-05-22 08:33:47,434: ERROR/MainProcess] Process 'ForkPoolWorker-9' pid:17 exited with 'signal 9 (SIGKILL)'
[2024-05-22 08:33:47,608: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL) Job: 1.')
Traceback (most recent call last):
  File "/data/project/editgroups/www/python/venv/lib/python3.11/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.einfo.ExceptionWithTraceback: 
"""
Traceback (most recent call last):
  File "/data/project/editgroups/www/python/venv/lib/python3.11/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 1.
"""
```

**Comment by wetneb** [comment]
Fixed by b8b3937c8f3dd55c944cb7d03b6b46d51e5e75e7
