### ISSUE TITLE
MySQL server is gone away

### ISSUE THREAD

**Issue by wetneb** [Wikidata/editgroups#28]
The listener dies often because of this:

```
Traceback (most recent call last):
  File "listener.py", line 38, in <module>
    Edit.ingest_edits(batch)
  File "/data/project/editgroups/www/python/src/store/models.py", line 381, in ingest_edits
    for tool in tools:
  File "/data/project/editgroups/listener_venv/lib/python3.5/site-packages/django/db/models/query.py", line 268, in __iter__
    self._fetch_all()
  File "/data/project/editgroups/listener_venv/lib/python3.5/site-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/data/project/editgroups/listener_venv/lib/python3.5/site-packages/caching/base.py", line 139, in __iter__
    for obj in iterator():
  File "/data/project/editgroups/listener_venv/lib/python3.5/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/data/project/editgroups/listener_venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/data/project/editgroups/listener_venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/data/project/editgroups/listener_venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/data/project/editgroups/listener_venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/data/project/editgroups/listener_venv/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/data/project/editgroups/listener_venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/data/project/editgroups/listener_venv/lib/python3.5/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/data/project/editgroups/listener_venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/data/project/editgroups/listener_venv/lib/python3.5/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/data/project/editgroups/listener_venv/lib/python3.5/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (2006, 'MySQL server has gone away')
```

**Comment by seansan** [comment]
update mysql connection timeout

**Comment by wetneb** [comment]
This seems to be a deployment-specific problem and it's not a big deal as long as the listener restarts automatically.
