### ISSUE TITLE
Migrate from GitHub to Wikimedia infrastructure

### ISSUE THREAD

**Issue by wetneb** [Wikidata/editgroups#3]
I would be in favour of migrating this project to the Wikimedia dev environment (Gerrit, Phabricator, …) instead of using GitHub.

**Comment by wetneb** [comment]
Actually, I uploaded my first change to Gerrit today, and it's really not practical at all.
- the UI is frankly uninviting and confusing
- installing `git-review` is required
and…
```
$ git review -d 491924
Traceback (most recent call last):
  File "/usr/bin/git-review", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/git_review/cmd.py", line 1741, in main
    _main()
  File "/usr/lib/python3/dist-packages/git_review/cmd.py", line 1639, in _main
    config['project'])
  File "/usr/lib/python3/dist-packages/git_review/cmd.py", line 1190, in fetch_review
    parse_exc=ReviewInformationNotFound)
  File "/usr/lib/python3/dist-packages/git_review/cmd.py", line 563, in query_reviews
    parse_exc=parse_exc)
  File "/usr/lib/python3/dist-packages/git_review/cmd.py", line 602, in query_reviews_over_http
    reviews = json.loads(request.text[4:])
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I don't want contributors to this repository to have to fix `git-review` before they can contribute to EditGroups.
